### PR TITLE
fix: skip meters endpoint if it returns a 401

### LINKED ISSUE #123: No longer able to authenticate Envoy-R after firmware update D3.18.10 (f0855e)
**Describe the bug**
Since December 16th, my Home Assistant integration has stopped working with Enphase.
I noticed a new firmware update got installed, likely around that time, considering the build date:
```
Current Software Version	D3.18.10 (f0855e)
Software Build Date	Mon Oct 30, 2023 07:21 PM GMT
```
I tried using the latest pyenphase directly, but haven't been able to run any of the examples from the documentation, failing to authenticate.

I'm not able to log into this endpoint it's failing on via the browser either - it prompts me for username/password ,but the old "Installer" and "Envoy" usernames on this old gateway no longer seem to be working. Also tried with the Enlighten username/password + generated token with no luck.

```
  File "%USER_PROFILE%\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pyenphase\envoy.py", line 231, in _request
    raise EnvoyAuthenticationRequired(
pyenphase.exceptions.EnvoyAuthenticationRequired: Authentication failed for http://192.168.1.84/ivp/meters with status 401, please check your username/password or token.
```

**To Reproduce**

**Additional context**

### PR DESCRIPTION
**Pull request by bdraco**
For D3.18.10 (f0855e) systems return 401 even if the user has access to the endpoint so we must skip it.

fixes #123

### CODE REVIEW

**Comment by dotMorten** [comment]
If this is merely skipping the endpoint does this mean we’ll no longer get per-inverter stats?

**Comment by bdraco** [comment]
I'm not sure why skipping the meters endpoint would affect the inverters endpoint?

**Comment by dotMorten** [comment]
Sorry I misread

**Review by joostlek — APPROVED** [review]

**Comment by bdraco** [comment]
Thanks

**Comment by dotMorten** [comment]
@bdraco Thinking some more about this.... I'm still confused. You skip the Meters endpoint sure, but even the Inverters endpoint returns 401, which if I'm understanding correctly also prevents me from now getting per-panel data? Ie calling `http://]gateway-ip]/api/v1/production/inverters` returns
```json
{
    "status": 401,
    "error": "",
    "info": "Authentication required",
    "moreInfo": ""
}
```

**Pull request merged**
